last: 20
images:
  docker.io:
    - calico/typha
    - calico/cni
    - calico/node
    - calico/kube-controllers
    - grafana/grafana # grafana charts
    - bats/bats # grafana charts
    - curlimages/curl # grafana charts
    - tkestack/kvass
    - thanosio/thanos
    - bitnami/thanos
    - bitnami/bitnami-shell
  docker.elastic.co:
    - elasticsearch/elasticsearch
    - kibana/kibana
    - logstash/logstash
    - beats/filebeat
    - beats/heartbeat
    - beats/packetbeat
    - beats/auditbeat
    - beats/journalbeat
    - beats/metricbeat
    - apm/apm-server
    - app-search/app-search
  quay.io:
    - coreos/flannel
    - ceph/ceph
    - cephcsi/cephcsi
    - csiaddons/k8s-sidecar
    - csiaddons/volumereplication-operator
    - prometheus/prometheus
    - prometheus/alertmanager
    - prometheus/pushgateway
    - prometheus/blackbox-exporter
    - prometheus/node-exporter
    - prometheus-operator/prometheus-config-reloader
    - prometheus-operator/prometheus-operator
    - brancz/kube-rbac-proxy
    - cilium/cilium
    - cilium/operator-generic
    - opstree/redis-sentinel
    - opstree/redis-operator
    - opstree/redis
    - opstree/redis-exporter
    - thanos/thanos
  registry.k8s.io:
    - etcd
    - pause
    - kube-proxy
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - coredns/coredns
    - dns/k8s-dns-node-cache
    - metrics-server/metrics-server
    - ingress-nginx/controller
    - ingress-nginx/kube-webhook-certgen
    - kube-state-metrics/kube-state-metrics
    - prometheus-adapter/prometheus-adapter
    - sig-storage/nfs-subdir-external-provisioner
    - sig-storage/csi-node-driver-registrar
    - sig-storage/csi-provisioner
    - sig-storage/csi-resizer
    - sig-storage/csi-snapshotter
    - sig-storage/csi-attacher
    - sig-storage/nfsplugin
    - quay.io/argoproj/argocd
  gcr.io:
    - kaniko-project/executor
    - google-samples/xtrabackup
    - tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    - tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers
    - tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    - tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter
    - tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
    - tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
    - tekton-releases/github.com/tektoncd/pipeline/cmd/nop
    - tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults
    - tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter
    - tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init
    - tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit
    - tekton-releases/github.com/tektoncd/triggers/cmd/controller
    - tekton-releases/github.com/tektoncd/triggers/cmd/webhook
    - tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink
    - tekton-releases/github.com/tektoncd/triggers/cmd/interceptors
    - tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard
